version: 3
endpoint: http://localhost:8080
admin_secret: hustlex_hasura_admin_secret
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://api:8081/hasura/actions
